export const shopActionTypes = {
  TOGGLE_NAV_HIDDEN: 'TOGGLE_NAV_HIDDEN',
  TOGGLE_SIDE_NAV_HIDDEN: 'TOGGLE_SIDE_NAV_HIDDEN',
  CART_NOTIFICATION_HIDDEN: 'CART_NOTIFICATION_HIDDEN',
  CART_NOTIFICATION_SHOW: 'CART_NOTIFICATION_SHOW',
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
}